### PR TITLE
Pin back NewRelic dependency.

### PR DESCRIPTION
**Pull request by jgerigmeyer**
In testing locally, it seems like this newrelic version upgrade was the culprit of the hanging WS events. I think we could potentially remove newrelic entirely? I don't love how their agent has to be so embedded into the processes.

I also don't think this necessarily needs to replace #1 and #2 -- though personally I might recommend we wait to upgrade channels-redis until a full version is released.

### CODE REVIEW

**Comment by jerivas** [comment]
Strong +1 on using a stable version of channels-redis

**Comment by jgerigmeyer** [comment]
> Strong +1 on using a stable version of channels-redis

@jerivas Do you want to update this PR to revert #1, remove newrelic entirely, and apply the other unrelated fix from #2?

**Comment by jerivas** [comment]
@jgerigmeyer will do

**Comment by jerivas** [comment]
Looks like removing new relic is the way to go https://github.com/SFDO-Tooling/MetaDeploy/pull/3458

**Comment by jgerigmeyer** [comment]
> Looks like removing new relic is the way to go https://github.com/SFDO-Tooling/MetaDeploy/pull/3458

Well, that was fast! 🚀 Only a few hours after I pointed out this issue to them. 😀

**Comment by jstvz** [comment]
> Well, that was fast! 🚀 Only a few hours after I pointed out this issue to them. 😀

@jgerigmeyer Out of curiosity, who did you tell?

**Comment by jerivas** [comment]
@jgerigmeyer I applied all changes but I'm seeing the WS disconnects during plan installation again 😕 Can you confirm?

**Comment by jgerigmeyer** [comment]
> @jgerigmeyer I applied all changes but I'm seeing the WS disconnects during plan installation again 😕 Can you confirm?

@jerivas WS events are working fine for me here -- I'm not seeing any disconnections during org creation or job installation.

**Comment by jgerigmeyer** [comment]
@jlantz I think this is ready for you to merge any time 👍

**Pull request merged**
